#!/bin/zsh
# Xcode Cloud runs this after cloning the repo. The IMPSY-AUv3 project is
# generated by xcodegen, so we download a pinned release binary before the
# workflow's build step.
#
# We do *not* use `brew install xcodegen`: Homebrew git-fetches its own repo
# (Homebrew/brew) during install, and Xcode Cloud's repo auto-discovery
# registers that as an "Additional Repository" the user has to connect —
# which breaks subsequent builds with a "Repository Issue: Xcode Cloud is
# unable to connect to https://github.com/Homebrew/brew" error.

set -euo pipefail

XCODEGEN_VERSION="2.45.4"
XCODEGEN_SHA256="090ec29491aad50aec10631bf6e62253fed733c50f3aab0f5ffc86bc170bdbef"
XCODEGEN_URL="https://github.com/yonaskolb/XcodeGen/releases/download/${XCODEGEN_VERSION}/xcodegen.zip"

cd "$CI_PRIMARY_REPOSITORY_PATH"

echo "ci_post_clone: downloading xcodegen ${XCODEGEN_VERSION}"
XCODEGEN_DIR="$(mktemp -d -t impsy-xcodegen)"
curl -fsSL -o "$XCODEGEN_DIR/xcodegen.zip" "$XCODEGEN_URL"
ACTUAL_SHA=$(shasum -a 256 "$XCODEGEN_DIR/xcodegen.zip" | awk '{print $1}')
if [[ "$ACTUAL_SHA" != "$XCODEGEN_SHA256" ]]; then
  echo "ci_post_clone: FAILED — xcodegen.zip SHA-256 mismatch"
  echo "  expected: $XCODEGEN_SHA256"
  echo "  actual:   $ACTUAL_SHA"
  exit 1
fi
unzip -q "$XCODEGEN_DIR/xcodegen.zip" -d "$XCODEGEN_DIR"
XCODEGEN_BIN="$XCODEGEN_DIR/xcodegen/bin/xcodegen"
chmod +x "$XCODEGEN_BIN"

echo "ci_post_clone: generating Xcode project"
"$XCODEGEN_BIN" generate

# Build TFLite xcframework. The local SPM package Packages/TensorFlowLite
# vends a binaryTarget pointing at a vendored xcframework that is not
# committed to git (assembled from prebuilt iOS + macOS slices). See
# scripts/build_tflite_xcframework.sh and issue #14.
echo "ci_post_clone: building TensorFlowLiteC.xcframework"
./scripts/build_tflite_xcframework.sh

# Xcode Cloud disables automatic SPM resolution, so it requires Package.resolved
# to be present in the generated .xcodeproj before the build step runs.
echo "ci_post_clone: installing Package.resolved into generated project"
SPM_DIR="IMPSY-AUv3.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
mkdir -p "$SPM_DIR"
cp ci_scripts/Package.resolved "$SPM_DIR/Package.resolved"

echo "ci_post_clone: done"
