#!/bin/zsh
# Xcode Cloud runs this after cloning the repo. The IMPSY-AUv3 project is
# generated by xcodegen — install it via Homebrew (preinstalled on the
# runners) and generate the .xcodeproj before the workflow's build step.

set -euo pipefail

echo "ci_post_clone: installing xcodegen via Homebrew"
brew install xcodegen

echo "ci_post_clone: generating Xcode project"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

echo "ci_post_clone: done"
